services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ["python", "/app/docker/entrypoint.py"]
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/portfolio"
      REDIS_URL: "redis://redis:6379/0"
      CACHE_BACKEND: "redis"
      CELERY_TASK_ALWAYS_EAGER: "False"
      SITE_BASE_URL: "http://127.0.0.1:8000"
      RUN_MIGRATIONS: "True"
      AUTO_CREATE_SUPERUSER: "True"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "admin12345"
      AUTO_RESET_SUPERUSER_PASSWORD: "True"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config worker -l info
    entrypoint: ["python", "/app/docker/entrypoint.py"]
    volumes:
      - .:/app
      - ./media:/app/media
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/portfolio"
      REDIS_URL: "redis://redis:6379/0"
      CACHE_BACKEND: "redis"
      CELERY_TASK_ALWAYS_EAGER: "False"
      SITE_BASE_URL: "http://127.0.0.1:8000"
      RUN_MIGRATIONS: "False"
      AUTO_CREATE_SUPERUSER: "True"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "admin12345"
      AUTO_RESET_SUPERUSER_PASSWORD: "True"
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  # media is bind-mounted from ./media

